# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0004_auto_20161212_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthdate',
            new_name='birthday',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
